# Generated by Django 5.1.4 on 2025-04-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_exam_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_exam',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='متن'),
        ),
    ]
