# Generated by Django 5.1.4 on 2025-04-30 16:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_module', '0001_initial'),
        ('lesson_module', '0001_initial'),
        ('sample_exam_module', '0002_alter_sample_exam_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sample_exam',
            new_name='SampleExam',
        ),
        migrations.RenameModel(
            old_name='ExamResultFile',
            new_name='SampleExamFiles',
        ),
    ]
