# Generated by Django 5.1.4 on 2025-02-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=120, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=120, verbose_name='آدرس سایت')),
                ('about_us', models.TextField(verbose_name='درباره ی ما')),
                ('is_main', models.BooleanField(db_index=True, default=False, verbose_name='اصلی / غیر اصلی')),
            ],
            options={
                'verbose_name': 'تنضیمات سایت',
                'verbose_name_plural': 'تنضیمات سایت',
            },
        ),
    ]
