# Generated by Django 5.1.4 on 2025-04-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='help_file',
            field=models.FileField(null=True, upload_to='', verbose_name='فایل راهنما'),
        ),
    ]
