# Generated by Django 5.1.4 on 2025-01-30 12:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='موضوع')),
                ('description', models.TextField(max_length=1500, verbose_name='توضیحات')),
                ('creation_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', models.DateField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('for_date', models.DateField(verbose_name='برای تاریخ')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه')),
                ('difficulty', models.IntegerField(choices=[(1, 'ساده'), (2, 'متوسط'), (3, 'سخت')], db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='سطح ساخته')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'تکلیف',
                'verbose_name_plural': 'تکالیف',
            },
        ),
        migrations.CreateModel(
            name='HomeworkCreatedFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه')),
                ('status', models.IntegerField(choices=[(1, 'انجام نشده'), (2, 'درحال انجام'), (3, 'انجام شده')], db_index=True, default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='وضعیت')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_class', to='homework_module.homework', verbose_name='تکلیف')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_homewrok', to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز')),
            ],
            options={
                'verbose_name': 'کاربر معین شده برای تکلیف',
                'verbose_name_plural': 'کاربران معین شده برای تکلیف',
            },
        ),
        migrations.CreateModel(
            name='HomeworkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / نشده')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه')),
                ('result', models.FileField(upload_to='homework_module/homework_results/', verbose_name='نتیجه تکلیف')),
                ('status', models.IntegerField(choices=[(1, 'ناقص'), (2, 'کامل')], db_index=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='نتیجه')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='homework_module.homework', verbose_name='امتحان')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_results', to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز')),
            ],
            options={
                'verbose_name': 'نتیجه امتحان',
                'verbose_name_plural': 'نتیجه امتحانات',
            },
        ),
    ]
