# Generated by Django 5.1.4 on 2025-03-13 12:46

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
import utils.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_module', '0003_class_teacher_alter_class_assigned_to'),
        ('lesson_module', '0002_alter_lesson_is_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='توضیحات بازخورد تکلیف')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / نشده')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه')),
            ],
            options={
                'verbose_name': 'بازخورد تکلیف',
                'verbose_name_plural': 'بازخورد تکالیف',
            },
        ),
        migrations.CreateModel(
            name='HomeworkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='توضیحات نتیجه تکلیف')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('result_status', models.IntegerField(choices=[(1, 'کامل'), (2, 'در انتظار'), (3, 'ناقص')], db_index=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='وضعیت نتیجه تکلیف')),
            ],
            options={
                'verbose_name': 'نتیجه تکلیف',
                'verbose_name_plural': 'نتیجه تکالیف',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='موضوع')),
                ('description', models.TextField(max_length=1500, verbose_name='توضیحات')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد تغییر')),
                ('for_date', django_jalali.db.models.jDateField(verbose_name='برای تاریخ')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه')),
                ('assigned_class', models.ManyToManyField(db_index=True, related_name='assigned_homeworks', to='class_module.class', verbose_name='برای کلاس')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='homeworks', to='lesson_module.lesson', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'تکلیف',
                'verbose_name_plural': 'تکالیف',
            },
        ),
        migrations.CreateModel(
            name='HomeworkFeedbackFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('file', models.FileField(db_index=True, upload_to='homework_module/homework_results/', validators=[utils.validators.MaxFileSize(5)], verbose_name='فایل های بازخورد تکلیف')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='homework_module.homeworkfeedback', verbose_name='تکلیف')),
            ],
            options={
                'verbose_name': 'فایل بازخورد تکلیف',
                'verbose_name_plural': 'فایل های بازخورد تکلیف',
            },
        ),
        migrations.CreateModel(
            name='HomeworkCreatedFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه')),
                ('status', models.IntegerField(choices=[(1, 'انجام شده'), (2, 'درحال انجام'), (3, 'انجام نشده')], db_index=True, default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='وضعیت')),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_homeworks', to='class_module.class', verbose_name='کلاس')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_homework', to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='homework_module.homework', verbose_name='تکلیف')),
                ('feedback', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to='homework_module.homeworkfeedback', verbose_name='بازخورد تکلیف')),
                ('result', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to='homework_module.homeworkresult', verbose_name='نتیجه تکلیف')),
            ],
            options={
                'verbose_name': 'کاربر معین شده برای تکلیف',
                'verbose_name_plural': 'کاربران معین شده برای تکلیف',
            },
        ),
        migrations.CreateModel(
            name='HomeworkResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('file', models.FileField(db_index=True, upload_to='homework_module/homework_results/', validators=[utils.validators.MaxFileSize(5)], verbose_name='فایل های نتیجه تکلیف')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='homework_module.homeworkresult', verbose_name='تکلیف')),
            ],
            options={
                'verbose_name': 'فایل نتیجه تکلیف',
                'verbose_name_plural': 'فایل های نتیجه تکلیف',
            },
        ),
    ]
