# Generated by Django 5.1.4 on 2025-04-27 18:26

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkfeedbackfile',
            name='file',
            field=models.FileField(upload_to='homework_module/homework_feedbacks/', validators=[utils.validators.MaxFileSize(5)], verbose_name='فایل های بازخورد تکلیف'),
        ),
        migrations.AlterField(
            model_name='homeworkresultfile',
            name='file',
            field=models.FileField(upload_to='homework_module/homework_results/', validators=[utils.validators.MaxFileSize(3)], verbose_name='فایل'),
        ),
    ]
