# Generated by Django 5.1.4 on 2025-01-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworkcreatedfor',
            old_name='student',
            new_name='assigned_to',
        ),
    ]
