# Generated by Django 5.1.4 on 2025-02-06 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0002_rename_student_homeworkcreatedfor_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط'),
        ),
    ]
