# Generated by Django 5.1.4 on 2025-02-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0003_rename_result_file_homeworkresultfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkresult',
            name='uuid',
        ),
    ]
