# Generated by Django 5.1.4 on 2025-02-06 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0003_alter_homework_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkcreatedfor',
            name='status',
            field=models.IntegerField(choices=[(1, 'انجام شده'), (2, 'درحال انجام'), (3, 'انجام نشده')], db_index=True, default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='وضعیت'),
        ),
    ]
