# Generated by Django 5.1.4 on 2025-02-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0004_remove_homeworkresult_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='is_active',
        ),
    ]
