# Generated by Django 5.1.4 on 2025-02-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0005_alter_homework_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkcreatedfor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='homeworkcreatedfor',
            name='is_delete',
        ),
    ]
