# Generated by Django 5.1.4 on 2025-02-12 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0005_remove_homework_is_active'),
        ('lesson_module', '0002_alter_lesson_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='homeworks', to='lesson_module.lesson', verbose_name='درس'),
        ),
    ]
