# Generated by Django 5.1.4 on 2025-02-08 11:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0006_remove_homeworkcreatedfor_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkresult',
            name='student',
        ),
        migrations.AddField(
            model_name='homeworkresult',
            name='created_by',
            field=models.ForeignKey(default='1', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='homework_results', to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط'),
        ),
        migrations.AlterField(
            model_name='homeworkcreatedfor',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_homework', to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز'),
        ),
        migrations.AlterField(
            model_name='homeworkresult',
            name='status',
            field=models.IntegerField(choices=[(1, 'کامل'), (2, 'ناقص')], db_index=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='نتیجه'),
        ),
    ]
