# Generated by Django 5.1.4 on 2025-02-12 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0006_homework_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworkresultfile',
            old_name='file',
            new_name='files',
        ),
    ]
