# Generated by Django 5.1.4 on 2025-02-09 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0007_remove_homeworkresult_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkresult',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='homeworkresult',
            name='homework',
        ),
        migrations.AddField(
            model_name='homeworkcreatedfor',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to='homework_module.homeworkresult', verbose_name='نتیجه تکلیف'),
        ),
    ]
