# Generated by Django 5.1.4 on 2025-02-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0007_rename_file_homeworkresultfile_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworkresultfile',
            old_name='files',
            new_name='file',
        ),
    ]
