# Generated by Django 5.1.4 on 2025-02-09 21:24

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0008_remove_homeworkresult_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworkresult',
            options={'verbose_name': 'نتیجه تکلیف', 'verbose_name_plural': 'نتیجه تکالیف'},
        ),
        migrations.RemoveField(
            model_name='homeworkresult',
            name='result',
        ),
        migrations.RemoveField(
            model_name='homeworkresult',
            name='status',
        ),
        migrations.AddField(
            model_name='homeworkcreatedfor',
            name='creation_date',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد شدن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeworkcreatedfor',
            name='modify_date',
            field=models.DateField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AddField(
            model_name='homeworkcreatedfor',
            name='result_description',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='توضیحات نتیجه تکلیف'),
        ),
        migrations.AddField(
            model_name='homeworkcreatedfor',
            name='result_status',
            field=models.IntegerField(choices=[(1, 'کامل'), (2, 'در انتظار'), (3, 'ناقص')], db_index=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='وضعیت نتیجه تکلیف'),
        ),
        migrations.AddField(
            model_name='homeworkresult',
            name='creation_date',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد شدن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeworkresult',
            name='modify_date',
            field=models.DateField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AddField(
            model_name='homeworkresult',
            name='result_description',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='توضیحات نتیجه تکلیف'),
        ),
        migrations.AlterField(
            model_name='homeworkcreatedfor',
            name='result',
            field=models.FileField(null=True, upload_to='homework_module/homework_results/', verbose_name='نتیجه تکلیف'),
        ),
    ]
