# Generated by Django 5.1.4 on 2025-02-13 10:33

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0008_rename_files_homeworkresultfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='creation_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='for_date',
            field=django_jalali.db.models.jDateField(verbose_name='برای تاریخ'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='modify_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AlterField(
            model_name='homeworkcreatedfor',
            name='creation_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AlterField(
            model_name='homeworkcreatedfor',
            name='modify_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AlterField(
            model_name='homeworkfeedback',
            name='creation_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AlterField(
            model_name='homeworkfeedback',
            name='modify_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AlterField(
            model_name='homeworkresult',
            name='creation_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AlterField(
            model_name='homeworkresult',
            name='modify_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AlterField(
            model_name='homeworkresultfile',
            name='creation_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AlterField(
            model_name='homeworkresultfile',
            name='modify_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
    ]
