# Generated by Django 5.1.4 on 2025-02-15 21:54

import django.db.models.deletion
import django_jalali.db.models
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0009_alter_homework_creation_date_alter_homework_for_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='modify_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد تغییر'),
        ),
        migrations.CreateModel(
            name='HomeworkFeedbackFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('file', models.FileField(db_index=True, upload_to='homework_module/homework_results/', validators=[utils.validators.validate_file_size], verbose_name='فایل های بازخورد تکلیف')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='homework_module.homeworkfeedback', verbose_name='تکلیف')),
            ],
            options={
                'verbose_name': 'فایل بازخورد تکلیف',
                'verbose_name_plural': 'فایل های بازخورد تکلیف',
            },
        ),
    ]
