# Generated by Django 5.1.4 on 2025-02-09 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0009_alter_homeworkresult_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', models.DateField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('result_file', models.FileField(null=True, upload_to='homework_module/homework_results/', verbose_name='نتیجه تکلیف')),
                ('assigned_homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='homework_module.homeworkcreatedfor', verbose_name='تکلیف')),
            ],
            options={
                'verbose_name': 'فایل نتیجه تکلیف',
                'verbose_name_plural': 'فایل های نتیجه تکلیف',
            },
        ),
    ]
