# Generated by Django 5.1.4 on 2025-02-16 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_module', '0002_alter_class_creation_date_alter_class_modify_date'),
        ('homework_module', '0010_alter_homework_modify_date_homeworkfeedbackfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='homeworkcreatedfor',
            name='assigned_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_homeworks', to='class_module.class', verbose_name='کلاس'),
            preserve_default=False,
        ),
    ]
