# Generated by Django 5.1.4 on 2025-02-09 22:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0011_remove_homeworkcreatedfor_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='توضیحات بازخورد تکلیف')),
                ('creation_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', models.DateField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / نشده')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه')),
            ],
            options={
                'verbose_name': 'بازخورد تکلیف',
                'verbose_name_plural': 'بازخورد تکالیف',
            },
        ),
        migrations.RemoveField(
            model_name='homeworkcreatedfor',
            name='result_description',
        ),
        migrations.RemoveField(
            model_name='homeworkcreatedfor',
            name='result_status',
        ),
        migrations.RemoveField(
            model_name='homeworkcreatedfor',
            name='status',
        ),
        migrations.RemoveField(
            model_name='homeworkresult',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='homeworkresult',
            name='uuid',
        ),
        migrations.AddField(
            model_name='homeworkcreatedfor',
            name='result',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to='homework_module.homeworkresult', verbose_name='نتیجه تکلیف'),
        ),
        migrations.AddField(
            model_name='homeworkresult',
            name='result_status',
            field=models.IntegerField(choices=[(1, 'کامل'), (2, 'در انتظار'), (3, 'ناقص')], db_index=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='وضعیت نتیجه تکلیف'),
        ),
        migrations.AddField(
            model_name='homeworkresult',
            name='status',
            field=models.IntegerField(choices=[(1, 'انجام شده'), (2, 'درحال انجام'), (3, 'انجام نشده')], db_index=True, default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='homeworkresult',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده'),
        ),
        migrations.AlterField(
            model_name='homeworkresultfile',
            name='assigned_homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='homework_module.homeworkresult', verbose_name='تکلیف نتیجه'),
        ),
        migrations.AlterField(
            model_name='homeworkresultfile',
            name='result_file',
            field=models.FileField(null=True, upload_to='homework_module/homework_results/', verbose_name='فایل های نتیجه تکلیف'),
        ),
        migrations.AddField(
            model_name='homeworkcreatedfor',
            name='feedback',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to='homework_module.homeworkfeedback', verbose_name='بازخورد تکلیف'),
        ),
    ]
