# Generated by Django 5.1.4 on 2025-02-09 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0012_homeworkfeedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkresult',
            name='status',
        ),
        migrations.AddField(
            model_name='homeworkcreatedfor',
            name='status',
            field=models.IntegerField(choices=[(1, 'انجام شده'), (2, 'درحال انجام'), (3, 'انجام نشده')], db_index=True, default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='وضعیت'),
        ),
    ]
