# Generated by Django 5.1.4 on 2025-02-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0013_remove_homeworkresult_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkresultfile',
            name='assigned_homework',
        ),
        migrations.AddField(
            model_name='homeworkresult',
            name='assigned_result',
            field=models.ManyToManyField(blank=True, related_name='homework', to='homework_module.homeworkresultfile', verbose_name='نتایج تکلیف'),
        ),
        migrations.AlterField(
            model_name='homeworkresultfile',
            name='result_file',
            field=models.FileField(default=1, upload_to='homework_module/homework_results/', verbose_name='فایل های نتیجه تکلیف'),
            preserve_default=False,
        ),
    ]
