# Generated by Django 5.1.4 on 2025-02-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_module', '0015_rename_assigned_result_homeworkresult_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworkfeedback',
            old_name='feedback_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='homeworkresult',
            old_name='result_description',
            new_name='description',
        ),
    ]
