# Generated by Django 5.1.4 on 2025-04-20 23:02

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, verbose_name='نام کلاس')),
                ('school_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='نام آموزشگاه (مدرسه)')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد تغییر')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / نشده')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='شناسه')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_classes', to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_classes', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('teacher', models.ManyToManyField(blank=True, related_name='assigned_teacher_role', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس ها',
            },
        ),
    ]
