# Generated by Django 5.1.4 on 2025-02-12 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, verbose_name='نام کلاس')),
                ('school_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='نام آموزشگاه (مدرسه)')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / نشده')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='شناسه')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_classes', to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_classes', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس ها',
            },
        ),
        migrations.CreateModel(
            name='ClassTeacherRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='class_module.class', verbose_name='برای کلاس')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='lesson_module.lesson', verbose_name='درس')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'نفش معلم در کلاس',
                'verbose_name_plural': 'نقش های معلم در کلاس ها',
            },
        ),
    ]
