# Generated by Django 5.1.4 on 2025-01-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='class_name',
        ),
        migrations.AddField(
            model_name='class',
            name='school_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='نام آموزشگاه (مدرسه)'),
        ),
    ]
