# Generated by Django 5.1.4 on 2025-02-13 10:33

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='creation_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='class',
            name='modify_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
