# Generated by Django 5.1.4 on 2025-01-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_module', '0002_rename_name_class_class_name_class_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='description',
        ),
    ]
