# Generated by Django 5.1.4 on 2025-01-30 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_module', '0003_remove_class_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(null=True, related_name='assigned_classes', to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز'),
        ),
    ]
