# Generated by Django 5.1.4 on 2025-01-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_module', '0004_alter_class_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='students',
            new_name='assigned_to',
        ),
    ]
