# Generated by Django 5.1.4 on 2025-01-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_module', '0005_rename_students_class_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classteacherrole',
            name='lesson',
        ),
    ]
