# Generated by Django 5.1.4 on 2025-01-31 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_module', '0006_remove_classteacherrole_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_classes', to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز'),
        ),
    ]
