# Generated by Django 5.1.4 on 2025-02-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_module', '0010_classteacherrole_lesson'),
        ('lesson_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacherrole',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='lesson_module.lesson', verbose_name='درس'),
        ),
    ]
