# Generated by Django 5.1.4 on 2025-02-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_module', '0011_alter_classteacherrole_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classteacherrole',
            old_name='for_class',
            new_name='assigned_class',
        ),
    ]
