# Generated by Django 5.1.4 on 2025-04-27 19:29

import django.db.models.deletion
import django_jalali.db.models
import utils.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_module', '0001_initial'),
        ('lesson_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='موضوع')),
                ('text', models.TextField(blank=True, max_length=10000, null=True, verbose_name='موضوع')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه')),
                ('assigned_class', models.ManyToManyField(db_index=True, related_name='assigned_notes', to='class_module.class', verbose_name='برای کلاس')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_notes', to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='notes', to='lesson_module.lesson', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'نکات درسی',
                'verbose_name_plural': 'نکات درسی',
            },
        ),
        migrations.CreateModel(
            name='ExamResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('file', models.FileField(upload_to='note_module/', validators=[utils.validators.MaxFileSize(3)], verbose_name='فایل')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='note_module.note', verbose_name='برای نکته درسی')),
            ],
        ),
    ]
