# Generated by Django 5.1.4 on 2025-04-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_module', '0002_alter_note_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamResultFile',
            new_name='NoteFiles',
        ),
    ]
