# Generated by Django 5.1.4 on 2025-01-30 12:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حدف شده / نشده')),
                ('type', models.IntegerField(choices=[(1, 'عضویت دانش آموز'), (2, 'عضویت معلم')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='نوع')),
                ('assigned_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_invitations', to='class_module.class', verbose_name='معین شده برای کلاس')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست ها',
            },
        ),
        migrations.CreateModel(
            name='InvitationAssignedTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حدف شده / نشده')),
                ('status', models.IntegerField(choices=[(1, 'قبول شده'), (2, 'رد شده'), (3, 'در انتظار')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='وضعیت')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_invitation', to=settings.AUTH_USER_MODEL, verbose_name='معین شده برای')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='invitation_module.invitation', verbose_name='ریکوئست')),
            ],
            options={
                'verbose_name': 'کاربران معین شده برای درخواست',
                'verbose_name_plural': 'کاربر معین شده برای درخواست',
            },
        ),
    ]
