# Generated by Django 5.1.4 on 2025-01-30 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationassignedto',
            name='status',
            field=models.IntegerField(choices=[(1, 'قبول شده'), (2, 'رد شده'), (3, 'در انتظار')], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='وضعیت'),
        ),
    ]
