# Generated by Django 5.1.4 on 2025-02-13 10:33

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='creation_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
    ]
