# Generated by Django 5.1.4 on 2025-02-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_module', '0002_alter_invitation_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='invitationassignedto',
            name='is_active',
        ),
    ]
