# Generated by Django 5.1.4 on 2025-01-30 20:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_module', '0002_alter_invitationassignedto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationassignedto',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه'),
        ),
    ]
