# Generated by Django 5.1.4 on 2025-01-30 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_module', '0004_invitation_lesson'),
        ('lesson_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='lesson',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_invites', to='lesson_module.lesson', verbose_name='معین شده برای درس'),
        ),
    ]
