# Generated by Django 5.1.4 on 2025-01-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_module', '0005_alter_invitation_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='lesson',
        ),
    ]
