# Generated by Django 5.1.4 on 2025-02-01 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_module', '0007_alter_invitation_created_by'),
        ('lesson_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationassignedto',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='lesson_module.lesson', verbose_name='درس'),
        ),
    ]
