# Generated by Django 5.1.4 on 2025-02-01 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_module', '0009_alter_invitationassignedto_lesson'),
        ('lesson_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationassignedto',
            name='lesson',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='lesson_module.lesson', verbose_name='درس'),
        ),
    ]
