# Generated by Django 5.1.4 on 2025-02-02 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_module', '0010_alter_invitationassignedto_lesson'),
        ('lesson_module', '0002_alter_lesson_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationassignedto',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='lesson_module.lesson', verbose_name='درس'),
        ),
    ]
