from typing import Any
from django.db import models
import jdatetime


class JDateTimeField(models.DateTimeField):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def from_db_value(self, value: Any, expression, connection: Any) -> jdatetime.datetime: ...
    def deconstruct(self) -> Any: ...
    def clean(self, value: Any, model_instance: models.Model | None) -> Any: ...


class JDateField(models.DateField):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def from_db_value(self, value: Any, expression, connection: Any) -> jdatetime.date: ...
    def deconstruct(self) -> Any: ...
    def clean(self, value: Any, model_instance: models.Model | None) -> Any: ...
