from django.core.files.uploadedfile import UploadedFile
from django.forms import ValidationError


class MaxFileSize:
    def __init__(self, max_size: int | None = None) -> None: ...
    def __call__(self, value: list[UploadedFile]) -> ValidationError | None: ...
    def __eq__(self, other: MaxFileSize) -> bool: ...


class MinFileSize:
    def __init__(self, min_size: int | None = None) -> None: ...
    def __call__(self, value: list[UploadedFile]) -> ValidationError | None: ...
    def __eq__(self, other: MinFileSize) -> bool: ...
