# Generated by Django 5.1.4 on 2025-04-20 23:02

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='آدرس ایمیل')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='موضوع')),
                ('message', models.TextField(max_length=1500, verbose_name='متن پیام')),
                ('admin_message', models.TextField(blank=True, max_length=1500, null=True, verbose_name='متن جواب')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('is_read_by_admin', models.BooleanField(db_index=True, default=False, verbose_name='خوانده شده / نشده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
    ]
