# Generated by Django 5.1.4 on 2025-02-13 10:33

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='admin_message',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='متن جواب'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_read_by_admin',
            field=models.BooleanField(db_index=True, default=False, verbose_name='خوانده شده / نشده'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='creation_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='modify_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
