# Generated by Django 5.1.4 on 2025-02-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
