# Generated by Django 5.1.4 on 2025-04-20 23:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar_navbar_theme', models.CharField(choices=[('theme-1-active', 'سفید - سیاه'), ('theme-2-active', 'سیاه - سفید'), ('theme-3-active', 'سفید - سیاه کامل'), ('theme-4-active', 'سیاه - سفید کامل'), ('theme-5-active', 'سفید - سفید'), ('theme-6-active', 'سیاه - سیاه')], db_index=True, default='theme-6-active', max_length=14)),
                ('sidebar_primary_color', models.CharField(choices=[('pimary-color-red', 'قرمز'), ('pimary-color-blue', 'آبی'), ('pimary-color-green', 'سبز'), ('pimary-color-yellow', 'زرد'), ('pimary-color-pink', 'صورتی'), ('pimary-color-orange', 'نارنجی'), ('pimary-color-gold', 'طلایی'), ('pimary-color-silver', 'نقره ای')], db_index=True, default='pimary-color-blue', max_length=19)),
            ],
            options={
                'verbose_name': 'تنظیمات کاربر',
                'verbose_name_plural': 'تنظیمات کاربران',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('active_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('profile_image', models.FileField(default='/profile_images/default.jpg', upload_to='profile_images/', verbose_name='تصویر پروفایل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('settings', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account_module.accountsettings', verbose_name='تنضیمات')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
