# Generated by Django 5.1.4 on 2025-02-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(default='hichi', max_length=120, verbose_name='نام کامل'),
        ),
    ]
