# Generated by Django 5.1.4 on 2025-02-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='primary_theme',
            field=models.CharField(choices=[('theme-1-active', 'سفید - سیاه'), ('theme-2-active', 'سیاه - سفید'), ('theme-3-active', 'سفید - سیاه کامل'), ('theme-4-active', 'سیاه - سفید کامل'), ('theme-5-active', 'سفید - سفید'), ('theme-6-active', 'سیاه - سیاه')], db_index=True, default='theme-6-active', max_length=14),
        ),
    ]
