# Generated by Django 5.1.4 on 2025-02-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_remove_account_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsettings',
            name='primary_theme',
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='pimary_color',
            field=models.CharField(choices=[('pimary-color-red', 'سفید - سیاه'), ('pimary-color-blue', 'سیاه - سفید'), ('pimary-color-green', 'سفید - سیاه کامل'), ('pimary-color-yellow', 'سیاه - سفید کامل'), ('pimary-color-pink', 'سفید - سفید'), ('pimary-color-orange', 'سیاه - سیاه'), ('pimary-color-gold', 'سیاه - سیاه'), ('pimary-color-silver', 'سیاه - سیاه')], db_index=True, default='pimary-color-blue', max_length=19),
        ),
    ]
