# Generated by Django 5.1.4 on 2025-02-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_account_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='نام کامل'),
        ),
    ]
