# Generated by Django 5.1.4 on 2025-02-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_account_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='full_name',
        ),
    ]
