# Generated by Django 5.1.4 on 2025-02-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_remove_accountsettings_primary_theme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsettings',
            old_name='pimary_color',
            new_name='sidebar_primary_color',
        ),
    ]
