# Generated by Django 5.1.4 on 2025-02-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_rename_pimary_color_accountsettings_sidebar_primary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account_module.accountsettings', verbose_name='توضیحات'),
        ),
    ]
