# Generated by Django 5.1.4 on 2025-02-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_accountsettings_account_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='sidebar_navbar_theme',
            field=models.CharField(choices=[('theme-1-active', 'سفید - سیاه'), ('theme-2-active', 'سیاه - سفید'), ('theme-3-active', 'سفید - سیاه کامل'), ('theme-4-active', 'سیاه - سفید کامل'), ('theme-5-active', 'سفید - سفید'), ('theme-6-active', 'سیاه - سیاه')], db_index=True, default='theme-6-active', max_length=14),
        ),
    ]
