# Generated by Django 5.1.4 on 2025-02-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_alter_account_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='sidebar_primary_color',
            field=models.CharField(choices=[('pimary-color-red', 'قرمز'), ('pimary-color-blue', 'آبی'), ('pimary-color-green', 'سبز'), ('pimary-color-yellow', 'زرد'), ('pimary-color-pink', 'صورتی'), ('pimary-color-orange', 'نارنجی'), ('pimary-color-gold', 'طلایی'), ('pimary-color-silver', 'نقره ای')], db_index=True, default='pimary-color-blue', max_length=19),
        ),
    ]
