# Generated by Django 5.1.4 on 2025-02-02 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_accountsettings_sidebar_navbar_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsettings',
            options={'verbose_name': 'تنظیمات کاربر', 'verbose_name_plural': 'تنظیمات کاربران'},
        ),
    ]
