# Generated by Django 5.1.4 on 2025-02-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_alter_accountsettings_sidebar_primary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.FileField(null=True, upload_to='profile_images/', verbose_name='تصویر پروفایل'),
        ),
    ]
