# Generated by Django 5.1.4 on 2025-02-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0007_alter_accountsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.FileField(null=True, upload_to='account_module/profile_images/', verbose_name='تصویر پروفایل'),
        ),
    ]
