# Generated by Django 5.1.4 on 2025-02-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0008_alter_account_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.FileField(default='/profile_images/default.jpg', upload_to='profile_images/', verbose_name='تصویر پروفایل'),
        ),
    ]
