# Generated by Django 5.1.4 on 2025-04-20 23:02

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
import utils.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_module', '0001_initial'),
        ('lesson_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='توضیحات')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / نشده')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه')),
            ],
            options={
                'verbose_name': 'بازخورد امتحان',
                'verbose_name_plural': 'بازخورد امتحان',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(db_index=True, default=0, verbose_name='جواب های درست')),
                ('not_answered', models.IntegerField(db_index=True, default=0, verbose_name='جواب های داده نشده')),
                ('incorrect_answers', models.IntegerField(db_index=True, default=0, verbose_name='جواب های نادرست')),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='توضیحات')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / نشده')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه')),
                ('result', models.IntegerField(choices=[(1, 'قبول شده'), (2, 'رد شده')], db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='نتیجه امتحان')),
            ],
            options={
                'verbose_name': 'نتیجه امتحان',
                'verbose_name_plural': 'نتیجه امتحانات',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='موضوع')),
                ('description', models.TextField(max_length=1500, verbose_name='توضیحات')),
                ('for_date', django_jalali.db.models.jDateField(verbose_name='برای تاریخ')),
                ('questions', models.IntegerField(default=20, verbose_name='تعداد سوالات')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه')),
                ('duration', models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='مدت زمان')),
                ('status', models.IntegerField(choices=[(1, 'انجام شده'), (2, 'انجام نشده')], db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='وضعیت')),
                ('difficulty', models.IntegerField(choices=[(1, 'ساده'), (2, 'متوسط'), (3, 'سخت')], db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='سطح سختی')),
                ('assigned_class', models.ManyToManyField(db_index=True, related_name='assigned_exams', to='class_module.class', verbose_name='برای کلاس')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exams', to='lesson_module.lesson', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'امتحان',
                'verbose_name_plural': 'امتحانات',
            },
        ),
        migrations.CreateModel(
            name='ExamFeedbackFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('file', models.FileField(null=True, upload_to='exam_module/exam_feedbacks/', validators=[utils.validators.MaxFileSize(3)], verbose_name='فایل')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='exam_module.examfeedback', verbose_name='امتحان')),
            ],
            options={
                'verbose_name': 'فایل بازخورد امتحان',
                'verbose_name_plural': 'فایل های بازخورد امتحانات',
            },
        ),
        migrations.CreateModel(
            name='ExamCreatedFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه')),
                ('status', models.IntegerField(choices=[(1, 'انجام شده'), (2, 'انجام نشده')], db_index=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='وضعیت')),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to='class_module.class', verbose_name='کلاس')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams', to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='exam_module.exam', verbose_name='امتحان')),
                ('feedback', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='exam_module.examfeedback', verbose_name='بازخورد امتحان')),
                ('result', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='exam_module.examresult', verbose_name='نتیجه امتحان')),
            ],
            options={
                'verbose_name': 'کاربر معین شده برای امتحان',
                'verbose_name_plural': 'کاربران معین شده برای امتحانات',
            },
        ),
        migrations.CreateModel(
            name='ExamResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('modify_date', django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('file', models.FileField(null=True, upload_to='exam_module/exam_results/', validators=[utils.validators.MaxFileSize(3)], verbose_name='فایل')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam_module.examresult', verbose_name='امتحان')),
            ],
            options={
                'verbose_name': 'فایل نتیجه امتحان',
                'verbose_name_plural': 'فایل های نتیجه امتحانات',
            },
        ),
    ]
