# Generated by Django 5.1.4 on 2025-01-30 12:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='موضوع')),
                ('description', models.TextField(max_length=1500, verbose_name='توضیحات')),
                ('for_date', models.DateField(verbose_name='برای تاریخ')),
                ('duration', models.DurationField(verbose_name='مدت زمان')),
                ('questions', models.IntegerField(default=20, verbose_name='تعداد سوالات')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / حذف نشده')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیرفعال')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه')),
                ('creation_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن')),
                ('status', models.IntegerField(choices=[(1, 'ایجاد نشده'), (2, 'ایجاد شده')], db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='وضعیت')),
                ('difficulty', models.IntegerField(choices=[(1, 'ساده'), (2, 'متوسط'), (3, 'سخت')], db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='سطح ساخته')),
                ('assigned_to', models.ManyToManyField(db_index=True, related_name='assigned_exams', to='class_module.class', verbose_name='ساخته شده برای')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'امتحان',
                'verbose_name_plural': 'امتحانات',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(verbose_name='جواب های درست')),
                ('incorrect_answers', models.IntegerField(verbose_name='جواب های نادرست')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده / نشده')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='exam_module.exam', verbose_name='امتحان')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز')),
            ],
            options={
                'verbose_name': 'نتیجه امتحان',
                'verbose_name_plural': 'نتیجه امتحانات',
            },
        ),
    ]
