# Generated by Django 5.1.4 on 2025-04-27 18:26

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examfeedbackfile',
            name='file',
            field=models.FileField(default=1, upload_to='exam_module/exam_feedbacks/', validators=[utils.validators.MaxFileSize(3)], verbose_name='فایل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examresultfile',
            name='file',
            field=models.FileField(default=1, upload_to='exam_module/exam_results/', validators=[utils.validators.MaxFileSize(3)], verbose_name='فایل'),
            preserve_default=False,
        ),
    ]
