# Generated by Django 5.1.4 on 2025-02-13 10:33

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='creation_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='for_date',
            field=django_jalali.db.models.jDateField(verbose_name='برای تاریخ'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='modify_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='creation_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='modify_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AlterField(
            model_name='examresultfile',
            name='creation_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
        migrations.AlterField(
            model_name='examresultfile',
            name='modify_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ ایجاد شدن'),
        ),
    ]
