# Generated by Django 5.1.4 on 2025-02-14 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_module', '0002_alter_exam_creation_date_alter_exam_for_date_and_more'),
        ('lesson_module', '0002_alter_lesson_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exams', to='lesson_module.lesson', verbose_name='درس'),
        ),
    ]
