# Generated by Django 5.1.4 on 2025-02-07 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_module', '0012_rename_for_class_classteacherrole_assigned_class'),
        ('exam_module', '0003_alter_exam_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='exam',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exams', to='class_module.class', verbose_name='ساخته شده برای'),
        ),
    ]
