# Generated by Django 5.1.4 on 2025-02-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_module', '0003_exam_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='is_active',
        ),
    ]
