# Generated by Django 5.1.4 on 2025-02-18 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_module', '0004_remove_exam_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'ساده'), (2, 'متوسط'), (3, 'سخت')], db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='سطح سختی'),
        ),
    ]
