# Generated by Django 5.1.4 on 2025-02-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_module', '0012_rename_for_class_classteacherrole_assigned_class'),
        ('exam_module', '0004_remove_exam_assigned_to_exam_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='exam',
            name='assigned_to',
            field=models.ManyToManyField(db_index=True, related_name='assigned_exams', to='class_module.class', verbose_name='ساخته شده برای'),
        ),
    ]
