# Generated by Django 5.1.4 on 2025-02-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_module', '0005_remove_exam_assigned_to_exam_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
